Algoritmo "Boson_treinaemntos_aula_5"
// Função:
// Autor :
// Data :
// Seção de Declarações
//
Var
   NOME : caractere
   SALARIO : real
   IDADE : inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   SALARIO <- 2500
   IDADE <- 37
   escreval ("Digite seu nome: ")
   leia     (NOME)
   escreva  ("O nome é : ")
   escreval (NOME)
   escreva  ("O salário é : ")
   escreval (SALARIO)
   escreva  ("Sua idade é : ")
   escreva  (IDADE)

Fimalgoritmo